pipeline {
    agent {
        docker {
            image 'maven:3.8-openjdk-11-slim'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages { 
        stage('Build') {
            when{
               changeset "**/worker/**" //when code chanfe on worker
             }
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            when{
               changeset "**/worker/**" //when code chanfe on worker
             }            
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
        stage('Package') {
            when{
               branch 'master'
               changeset "**/worker/**" //when code chanfe on worker
             }
            steps {
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true                   
                }
                
            }
        }
    }
    post { 
        always { 
            echo 'Build pipeline for worker app is complete'
            echo ' a test pipeline by manuh....'
        }
        failure { 
            slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success { 
            slackSend (channel: "instavote-cd", message: "Build Succeede - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            
        }
    }
}
